import "./globals.css";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import PageSettingProvider from "@/contexts/PageSettingContext";
import AdProvider from "@/contexts/AdContext";
import axios from "axios";
import BannerProvider from "@/contexts/bannerContext";
import CompanyContextProvider from "@/contexts/CompanyContext";

const TwElementCom = dynamic(
  () => import("@/components/twElementCom/twElementCom"),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// fetchAd
// const fetchAd = async () => {
//   try {
//     const response = await axios.get("http://localhost:3000/api/ad-setting");
//     const responseData = response.data;
//     const displayedAds = responseData.filter((i: any) => i?.status);
//     return displayedAds;
//   } catch (err) {
//
//   }
// };

const fetchBanner = async () => {
  const response = await fetch("http://localhost:3000/api/banner-setting", {
    cache: "no-store",
  });

  const data = await response.json();
  const displayedBanners = data
    .filter((i: any) => i?.status)
    .sort((a: any, b: any) => a.edition - b.edition);
  return displayedBanners;
};

const fetchAdTry = async () => {
  const response = await fetch("http://localhost:3000/api/ad-setting", {
    cache: "no-store",
  });

  const data = await response.json();
  const displayedAds = data
    .filter((i: any) => i?.status)
    .sort((a: any, b: any) => a.edition - b.edition);
  return displayedAds;
};
// fetchPageSetting
const fetchPageSetting = async () => {
  const response = await fetch("http://localhost:3000/api/page-setting", {
    // cache: "no-store",
    next: { revalidate: 5 },
  });
  const data = await response.json();

  return data;
};

// fetchCompanyProfile
// const fetchCompany = async () => {
//   const response = await fetch("http://localhost:3000/api/company-setting", {
//     cache: "no-store",
//     // next: { revalidate: 5 },
//   });
//   const data = await response.json();
//
//
//   return data;
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pageSettingData = await fetchPageSetting();
  const adData = await fetchAdTry();
  const bannerData = await fetchBanner();
  // const companyPageData = await fetchCompany();

  return (
    <html lang="en">
      <body className={inter.className}>
        <CompanyContextProvider>
          <BannerProvider bannerPage={bannerData}>
            <AdProvider adsPage={adData}>
              <PageSettingProvider pageSetting={pageSettingData.pageSetting}>
                {children}
                <TwElementCom />
              </PageSettingProvider>
            </AdProvider>
          </BannerProvider>
        </CompanyContextProvider>
      </body>
    </html>
  );
}
