import "./globals.css";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
// import MenuColumn from "@/components/MenuColumn/MenuColumn";
import SideNav from "@/components/webpanel/SideNav/SideNav";
import PageSettingProvider from "@/contexts/PageSettingContext";
import AdProvider from "@/contexts/AdContext";
import FilterContextProvider from "@/contexts/FilterContext";
import axios from "axios";
import BannerProvider from "@/contexts/bannerContext";

// const SideNav = dynamic(() => import("@/components/SideNav/SideNav"), {
//   ssr: false,
// });
// fetch filter function
const filterURL = "http://localhost:3000/api/filter-setting";
const fetchFilter = async () => {
  const response = await axios.get(filterURL);
  const data = await response.data.filters;

  console.log(data);
  return data;
};

const TwElementCom = dynamic(
  () => import("@/components/twElementCom/twElementCom"),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const filterData = await fetchFilter();
  return (
    <html lang="en" className="light">
      <body className={`${inter.className} `}>
        <BannerProvider>
          <AdProvider>
            <FilterContextProvider filters={filterData}>
              <PageSettingProvider>
                {/* {children} */}
                {/* <div className="bg-gray-200 h-[100vh] w-[300px]"> */}
                {/* <MenuColumn /> */}
                <SideNav _children={children} />
                {/* </div> */}
              </PageSettingProvider>
            </FilterContextProvider>
          </AdProvider>
        </BannerProvider>
        <TwElementCom />
      </body>
    </html>
  );
}
