import "./globals.css";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
// import MenuColumn from "@/components/MenuColumn/MenuColumn";
import SideNav from "@/components/webpanel/SideNav/SideNav";
import PageSettingProvider from "@/contexts/PageSettingContext";

// const SideNav = dynamic(() => import("@/components/SideNav/SideNav"), {
//   ssr: false,
// });

const TwElementCom = dynamic(
  () => import("@/components/twElementCom/twElementCom"),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body className={`${inter.className} `}>
        <PageSettingProvider>
          {/* {children} */}
          {/* <div className="bg-gray-200 h-[100vh] w-[300px]"> */}
          {/* <MenuColumn /> */}
          <SideNav _children={children} />
          {/* </div> */}

          <TwElementCom />
        </PageSettingProvider>
      </body>
    </html>
  );
}
